# Este archivo sirve para crear registros de prueba
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
Task.create(name: "Entender esta wea")
