# Este archivo sirve para crear registros de prueba
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta wea')
Task.create(name: 'entender esta cosa')
